// 2024 ICC Men's T20 World Cup squads — 12 teams, 11 players each.
// Default batting order reflects typical T20 XI from the tournament.

export const T20_TEAMS = [
  {
    id: 'india',
    name: 'India',
    flag: '🇮🇳',
    accent: '#1565C0',
    players: [
      { name: 'Rohit Sharma',       captain: true,  wk: false },
      { name: 'Virat Kohli',        captain: false, wk: false },
      { name: 'Suryakumar Yadav',   captain: false, wk: false },
      { name: 'Rishabh Pant',       captain: false, wk: true  },
      { name: 'Hardik Pandya',      captain: false, wk: false },
      { name: 'Shivam Dube',        captain: false, wk: false },
      { name: 'Ravindra Jadeja',    captain: false, wk: false },
      { name: 'Axar Patel',         captain: false, wk: false },
      { name: 'Kuldeep Yadav',      captain: false, wk: false },
      { name: 'Arshdeep Singh',     captain: false, wk: false },
      { name: 'Jasprit Bumrah',     captain: false, wk: false },
    ],
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    flag: '🇿🇦',
    accent: '#1B5E20',
    players: [
      { name: 'Reeza Hendricks',    captain: false, wk: false },
      { name: 'Quinton de Kock',    captain: false, wk: true  },
      { name: 'Aiden Markram',      captain: true,  wk: false },
      { name: 'Heinrich Klaasen',   captain: false, wk: false },
      { name: 'David Miller',       captain: false, wk: false },
      { name: 'Tristan Stubbs',     captain: false, wk: false },
      { name: 'Marco Jansen',       captain: false, wk: false },
      { name: 'Keshav Maharaj',     captain: false, wk: false },
      { name: 'Kagiso Rabada',      captain: false, wk: false },
      { name: 'Anrich Nortje',      captain: false, wk: false },
      { name: 'Tabraiz Shamsi',     captain: false, wk: false },
    ],
  },
  {
    id: 'england',
    name: 'England',
    flag: '🇬🇧',
    accent: '#0D47A1',
    players: [
      { name: 'Jos Buttler',        captain: true,  wk: true  },
      { name: 'Phil Salt',          captain: false, wk: false },
      { name: 'Jonny Bairstow',     captain: false, wk: false },
      { name: 'Harry Brook',        captain: false, wk: false },
      { name: 'Moeen Ali',          captain: false, wk: false },
      { name: 'Liam Livingstone',   captain: false, wk: false },
      { name: 'Sam Curran',         captain: false, wk: false },
      { name: 'Adil Rashid',        captain: false, wk: false },
      { name: 'Chris Jordan',       captain: false, wk: false },
      { name: 'Jofra Archer',       captain: false, wk: false },
      { name: 'Mark Wood',          captain: false, wk: false },
    ],
  },
  {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    accent: '#E65100',
    players: [
      { name: 'Travis Head',        captain: false, wk: false },
      { name: 'David Warner',       captain: false, wk: false },
      { name: 'Mitchell Marsh',     captain: true,  wk: false },
      { name: 'Glenn Maxwell',      captain: false, wk: false },
      { name: 'Tim David',          captain: false, wk: false },
      { name: 'Matthew Wade',       captain: false, wk: true  },
      { name: 'Marcus Stoinis',     captain: false, wk: false },
      { name: 'Pat Cummins',        captain: false, wk: false },
      { name: 'Mitchell Starc',     captain: false, wk: false },
      { name: 'Adam Zampa',         captain: false, wk: false },
      { name: 'Josh Hazlewood',     captain: false, wk: false },
    ],
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    flag: '🇵🇰',
    accent: '#1B5E20',
    players: [
      { name: 'Babar Azam',         captain: true,  wk: false },
      { name: 'Mohammad Rizwan',    captain: false, wk: true  },
      { name: 'Usman Khan',         captain: false, wk: false },
      { name: 'Fakhar Zaman',       captain: false, wk: false },
      { name: 'Iftikhar Ahmed',     captain: false, wk: false },
      { name: 'Shadab Khan',        captain: false, wk: false },
      { name: 'Imad Wasim',         captain: false, wk: false },
      { name: 'Shaheen Afridi',     captain: false, wk: false },
      { name: 'Haris Rauf',         captain: false, wk: false },
      { name: 'Naseem Shah',        captain: false, wk: false },
      { name: 'Abbas Afridi',       captain: false, wk: false },
    ],
  },
  {
    id: 'west-indies',
    name: 'West Indies',
    flag: '🏝️',
    abbr: 'WI',
    accent: '#B71C1C',
    players: [
      { name: 'Brandon King',        captain: false, wk: false },
      { name: 'Johnson Charles',     captain: false, wk: false },
      { name: 'Nicholas Pooran',     captain: false, wk: true  },
      { name: 'Rovman Powell',       captain: true,  wk: false },
      { name: 'Shai Hope',           captain: false, wk: false },
      { name: 'Andre Russell',       captain: false, wk: false },
      { name: 'Sherfane Rutherford', captain: false, wk: false },
      { name: 'Romario Shepherd',    captain: false, wk: false },
      { name: 'Alzarri Joseph',      captain: false, wk: false },
      { name: 'Akeal Hosein',        captain: false, wk: false },
      { name: 'Gudakesh Motie',      captain: false, wk: false },
    ],
  },
  {
    id: 'afghanistan',
    name: 'Afghanistan',
    flag: '🇦🇫',
    accent: '#4E342E',
    players: [
      { name: 'Rahmanullah Gurbaz', captain: false, wk: true  },
      { name: 'Ibrahim Zadran',     captain: false, wk: false },
      { name: 'Gulbadin Naib',      captain: false, wk: false },
      { name: 'Azmatullah Omarzai', captain: false, wk: false },
      { name: 'Mohammad Nabi',      captain: false, wk: false },
      { name: 'Karim Janat',        captain: false, wk: false },
      { name: 'Rashid Khan',        captain: true,  wk: false },
      { name: 'Noor Ahmad',         captain: false, wk: false },
      { name: 'Naveen ul Haq',      captain: false, wk: false },
      { name: 'Fareed Ahmad',       captain: false, wk: false },
      { name: 'Fazalhaq Farooqi',   captain: false, wk: false },
    ],
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    flag: '🇳🇿',
    accent: '#212121',
    players: [
      { name: 'Finn Allen',         captain: false, wk: false },
      { name: 'Devon Conway',       captain: false, wk: true  },
      { name: 'Kane Williamson',    captain: true,  wk: false },
      { name: 'Daryl Mitchell',     captain: false, wk: false },
      { name: 'Glenn Phillips',     captain: false, wk: false },
      { name: 'Mark Chapman',       captain: false, wk: false },
      { name: 'Michael Bracewell',  captain: false, wk: false },
      { name: 'Mitchell Santner',   captain: false, wk: false },
      { name: 'Tim Southee',        captain: false, wk: false },
      { name: 'Lockie Ferguson',    captain: false, wk: false },
      { name: 'Ish Sodhi',          captain: false, wk: false },
    ],
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    flag: '🇧🇩',
    accent: '#1B5E20',
    players: [
      { name: 'Tanzid Hasan Tamim', captain: false, wk: false },
      { name: 'Litton Das',         captain: false, wk: true  },
      { name: 'Najmul H. Shanto',   captain: true,  wk: false },
      { name: 'Soumya Sarkar',      captain: false, wk: false },
      { name: 'Towhid Hridoy',      captain: false, wk: false },
      { name: 'Shakib Al Hasan',    captain: false, wk: false },
      { name: 'Mahmudullah',        captain: false, wk: false },
      { name: 'Jaker Ali Anik',     captain: false, wk: false },
      { name: 'Rishad Hossain',     captain: false, wk: false },
      { name: 'Taskin Ahmed',       captain: false, wk: false },
      { name: 'Mustafizur Rahman',  captain: false, wk: false },
    ],
  },
  {
    id: 'sri-lanka',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    accent: '#1565C0',
    players: [
      { name: 'Pathum Nissanka',     captain: false, wk: false },
      { name: 'Kusal Mendis',        captain: false, wk: true  },
      { name: 'Charith Asalanka',    captain: false, wk: false },
      { name: 'Dhananjaya de Silva', captain: false, wk: false },
      { name: 'Dasun Shanaka',       captain: false, wk: false },
      { name: 'Wanindu Hasaranga',   captain: true,  wk: false },
      { name: 'Chamika Karunaratne', captain: false, wk: false },
      { name: 'Maheesh Theekshana',  captain: false, wk: false },
      { name: 'Nuwan Thushara',      captain: false, wk: false },
      { name: 'Matheesha Pathirana', captain: false, wk: false },
      { name: 'Dilshan Madushanka',  captain: false, wk: false },
    ],
  },
  {
    id: 'ireland',
    name: 'Ireland',
    flag: '🇮🇪',
    accent: '#1B5E20',
    players: [
      { name: 'Paul Stirling',      captain: true,  wk: false },
      { name: 'Lorcan Tucker',      captain: false, wk: true  },
      { name: 'Andrew Balbirnie',   captain: false, wk: false },
      { name: 'Harry Tector',       captain: false, wk: false },
      { name: 'Curtis Campher',     captain: false, wk: false },
      { name: 'Gareth Delany',      captain: false, wk: false },
      { name: 'Mark Adair',         captain: false, wk: false },
      { name: 'George Dockrell',    captain: false, wk: false },
      { name: 'Barry McCarthy',     captain: false, wk: false },
      { name: 'Josh Little',        captain: false, wk: false },
      { name: 'Craig Young',        captain: false, wk: false },
    ],
  },
  {
    id: 'usa',
    name: 'USA',
    flag: '🇺🇸',
    accent: '#B71C1C',
    players: [
      { name: 'Steven Taylor',          captain: false, wk: false },
      { name: 'Monank Patel',           captain: true,  wk: true  },
      { name: 'Aaron Jones',            captain: false, wk: false },
      { name: 'Andries Gous',           captain: false, wk: false },
      { name: 'Corey Anderson',         captain: false, wk: false },
      { name: 'Shadley van Schalkwyk',  captain: false, wk: false },
      { name: 'Milind Kumar',           captain: false, wk: false },
      { name: 'Harmeet Singh',          captain: false, wk: false },
      { name: 'Saurabh Netravalkar',    captain: false, wk: false },
      { name: 'Nosthush Kenjige',       captain: false, wk: false },
      { name: 'Ali Khan',               captain: false, wk: false },
    ],
  },
]
